### NEWS
GET http://localhost:3000/api/news

###
GET http://localhost:3000/api/news?limit=10&page=0&search_query=

###
GET http://localhost:3000/api/news?limit=5&page=1&category=Sex & Love

###
GET http://localhost:3000/api/custom-news?limit=5&page=0

### CUSTOM NEWS
GET http://localhost:3000/api/custom-news?limit=5&page=0

###
POST http://localhost:3000/api/custom-news
content-type: application/json

{
    "articleData": {
        "title": "String",
        "description": "String",
        "thumbnailLink": "String",
        "author": "sdf",
        "content": "String",
        "published": "Number",
        "created": "Number",
        "category": "String"
    }
}

###
PUT http://localhost:3000/api/custom-news/64e741c39bd1e48dd9bc74e0
content-type: application/json

{
    "articleData": {
        "title": "sdfjksdfnjsdkfhsd"
    }
}

###
DELETE http://localhost:3000/api/custom-news/64e73fadc8fab2304c4bdce7

###
POST http://localhost:3000/api/auth/signup
content-type: application/json

{
    "username": "davud",
    "password": "davud",
    "confirmPassword": "davud",
    "email": "davud@gmail.com"
}

###
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "davud@gmail.com",
    "password": "chkdsk34"
}

###
GET http://localhost:3000/api/users/liked-articles?email=davud@gmail.com
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjIxMzZmMTdkYTI1YzBmYjQ0NTdmNCIsImlhdCI6MTY5MzgzMTIzMiwiZXhwIjoxNjkzOTE3NjMyfQ.-Txz11fby68kyTPC78GEev4DdFJkZnD4KfovPkrKhew