### NEWS
GET http://localhost:3000/api/news

###
GET http://localhost:3000/api/news?limit=6&page=0&search_query=

###
GET http://localhost:3000/api/news?search_query=Jennifer Lopez, Demi Lovato, Bill Nye, And 26 Other Celebrities Who

###
GET http://localhost:3000/api/news?limit=5&page=1&category=Sex & Love

###
GET http://localhost:3000/api/news/delete-test?limit=700

###
GET http://localhost:3000/api/custom-news?limit=5&page=0

### CUSTOM NEWS
GET http://localhost:3000/api/custom-news

###
POST http://localhost:3000/api/custom-news
content-type: application/json

{
    "articleData": {
        "title": "String",
        "description": "String",
        "thumbnailLink": "String",
        "author": "sdf",
        "content": "String",
        "published": "Number",
        "created": "Number",
        "category": "String"
    }
}

###
PUT http://localhost:3000/api/custom-news/64e741c39bd1e48dd9bc74e0
content-type: application/json

{
    "articleData": {
        "title": "sdfjksdfnjsdkfhsd"
    }
}